version: "3.8"

services:
  web:
    container_name: code-name-web
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/home/project:ro
    env_file:
      - .env

  adminer:
    container_name: code-name-adminer
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - code-name

  db:
    container_name: code-name-db
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - code-name

volumes:
  postgres_data:

networks:
  code-name:
